apiVersion: v1
kind: Service
metadata:
  name: tickets-api
  namespace: {{ .Values.namespace }}
  labels:
    app: tickets-api
    {{- include "transaction-outbox.labels" . | nindent 4 }}
spec:
  type: {{ .Values.ticketsApi.service.type | default "ClusterIP" }}
  selector:
    app: tickets-api
  ports:
    - name: http
      port: 8080
      targetPort: 8080
    - name: metrics
      port: 9090
      targetPort: 9090
