DROP TABLE IF EXISTS charges;
DROP TABLE IF EXISTS tickets;
DROP TABLE IF EXISTS orders;
DROP TABLE IF EXISTS event_areas;
DROP TABLE IF EXISTS events;
DROP TABLE IF EXISTS producers;
DROP TABLE IF EXISTS locations;
