apiVersion: autoscaling/v2
kind: HorizontalPodAutoscaler
metadata:
  name: ingestion-api
  namespace: {{ .Values.namespace }}
  labels:
    {{- include "transaction-outbox.labels" . | nindent 4 }}
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: ingestion-api
  minReplicas: {{ .Values.ingestionApi.hpa.minReplicas }}
  maxReplicas: {{ .Values.ingestionApi.hpa.maxReplicas }}
  metrics:
    - type: Resource
      resource:
        name: cpu
        target:
          type: Utilization
          averageUtilization: {{ .Values.ingestionApi.hpa.cpuUtilization }}
    - type: Resource
      resource:
        name: memory
        target:
          type: Utilization
          averageUtilization: {{ .Values.ingestionApi.hpa.memoryUtilization }}
