// Package docs Code generated by swaggo/swag. DO NOT EDIT
package docs

import "github.com/swaggo/swag"

const docTemplate = `{
    "schemes": {{ marshal .Schemes }},
    "swagger": "2.0",
    "info": {
        "description": "{{escape .Description}}",
        "title": "{{.Title}}",
        "contact": {},
        "version": "{{.Version}}"
    },
    "host": "{{.Host}}",
    "basePath": "{{.BasePath}}",
    "paths": {
        "/api/v1/orders": {
            "post": {
                "description": "Accepts a request for tickets to an Event, durably stores it in the order outbox\nfor asynchronous relay to RabbitMQ (routed by eventType/eventSubtype). Idempotent on\nthe derived idempotency key (sourceOrderId + optional Idempotency-Key header).",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "orders"
                ],
                "summary": "Place a ticket order",
                "parameters": [
                    {
                        "type": "string",
                        "description": "Optional client-supplied idempotency key",
                        "name": "Idempotency-Key",
                        "in": "header"
                    },
                    {
                        "description": "Ticket order payload",
                        "name": "order",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/internal_adapter_http.OrderRequestDTO"
                        }
                    }
                ],
                "responses": {
                    "201": {
                        "description": "Created",
                        "schema": {
                            "$ref": "#/definitions/internal_adapter_http.OrderResponseDTO"
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "type": "object",
                            "additionalProperties": {
                                "type": "string"
                            }
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "type": "object",
                            "additionalProperties": {
                                "type": "string"
                            }
                        }
                    }
                }
            }
        },
        "/api/v1/webhooks/payments/{provider}": {
            "post": {
                "description": "Verifies the gateway's signature and lands the confirmation in payment_event_outbox\nfor asynchronous relay to fulfillment-consumer-worker. Idempotent on the gateway's own event id.",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "webhooks"
                ],
                "summary": "Receive a payment-gateway webhook",
                "parameters": [
                    {
                        "type": "string",
                        "description": "Configured gateway provider name (e.g. stripe, fake)",
                        "name": "provider",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "type": "object",
                            "additionalProperties": {
                                "type": "string"
                            }
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "type": "object",
                            "additionalProperties": {
                                "type": "string"
                            }
                        }
                    },
                    "404": {
                        "description": "Not Found",
                        "schema": {
                            "type": "object",
                            "additionalProperties": {
                                "type": "string"
                            }
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "type": "object",
                            "additionalProperties": {
                                "type": "string"
                            }
                        }
                    }
                }
            }
        },
        "/healthz": {
            "get": {
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "health"
                ],
                "summary": "Health check",
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "type": "object",
                            "additionalProperties": {
                                "type": "string"
                            }
                        }
                    }
                }
            }
        }
    },
    "definitions": {
        "internal_adapter_http.CustomerDTO": {
            "type": "object",
            "properties": {
                "document": {
                    "type": "string"
                },
                "email": {
                    "type": "string"
                },
                "name": {
                    "type": "string"
                }
            }
        },
        "internal_adapter_http.OrderRequestDTO": {
            "type": "object",
            "properties": {
                "customer": {
                    "$ref": "#/definitions/internal_adapter_http.CustomerDTO"
                },
                "eventId": {
                    "type": "string"
                },
                "eventName": {
                    "type": "string"
                },
                "eventSubtype": {
                    "type": "string"
                },
                "eventType": {
                    "type": "string"
                },
                "sourceOrderId": {
                    "type": "string"
                },
                "tickets": {
                    "type": "array",
                    "items": {
                        "$ref": "#/definitions/internal_adapter_http.TicketItemDTO"
                    }
                },
                "venue": {
                    "$ref": "#/definitions/internal_adapter_http.VenueDTO"
                }
            }
        },
        "internal_adapter_http.OrderResponseDTO": {
            "type": "object",
            "properties": {
                "idempotencyKey": {
                    "type": "string"
                },
                "orderId": {
                    "type": "string"
                },
                "status": {
                    "description": "\"accepted\" | \"duplicate\"",
                    "type": "string"
                }
            }
        },
        "internal_adapter_http.TicketItemDTO": {
            "type": "object",
            "properties": {
                "currency": {
                    "type": "string"
                },
                "id": {
                    "type": "string"
                },
                "price": {
                    "type": "number"
                },
                "row": {
                    "type": "string"
                },
                "seat": {
                    "type": "string"
                },
                "section": {
                    "type": "string"
                }
            }
        },
        "internal_adapter_http.VenueDTO": {
            "type": "object",
            "properties": {
                "city": {
                    "type": "string"
                },
                "id": {
                    "type": "string"
                },
                "name": {
                    "type": "string"
                }
            }
        }
    }
}`

// SwaggerInfo holds exported Swagger Info so clients can modify it
var SwaggerInfo = &swag.Spec{
	Version:          "1.0",
	Host:             "",
	BasePath:         "/",
	Schemes:          []string{},
	Title:            "Transaction Outbox — Event Ticket System Ingestion API",
	Description:      "Accepts ticket orders and payment-gateway webhook confirmations, durably storing\nboth in the transactional outbox for asynchronous relay to RabbitMQ.",
	InfoInstanceName: "swagger",
	SwaggerTemplate:  docTemplate,
	LeftDelim:        "{{",
	RightDelim:       "}}",
}

func init() {
	swag.Register(SwaggerInfo.InstanceName(), SwaggerInfo)
}
