// Package docs Code generated by swaggo/swag. DO NOT EDIT
package docs

import "github.com/swaggo/swag"

const docTemplate = `{
    "schemes": {{ marshal .Schemes }},
    "swagger": "2.0",
    "info": {
        "description": "{{escape .Description}}",
        "title": "{{.Title}}",
        "contact": {},
        "version": "{{.Version}}"
    },
    "host": "{{.Host}}",
    "basePath": "{{.BasePath}}",
    "paths": {
        "/api/v1/payments": {
            "post": {
                "description": "Accepts a payment-provider webhook-shaped event (PIX, BOLETO, TRANSFER, or any other method)\nand durably stores it in the outbox for asynchronous relay to RabbitMQ. Idempotent on the\nderived idempotency key (provider.name + eventId + optional Idempotency-Key header).",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "payments"
                ],
                "summary": "Ingest a payment event",
                "parameters": [
                    {
                        "type": "string",
                        "description": "Optional client-supplied idempotency key",
                        "name": "Idempotency-Key",
                        "in": "header"
                    },
                    {
                        "description": "Payment event payload",
                        "name": "payment",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/internal_adapter_http.PaymentRequest"
                        }
                    }
                ],
                "responses": {
                    "201": {
                        "description": "Created",
                        "schema": {
                            "$ref": "#/definitions/internal_adapter_http.PaymentResponse"
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "$ref": "#/definitions/internal_adapter_http.ErrorResponse"
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "$ref": "#/definitions/internal_adapter_http.ErrorResponse"
                        }
                    }
                }
            }
        },
        "/api/v1/payments/{id}": {
            "put": {
                "description": "Accepts a payment-provider webhook-shaped event (PIX, BOLETO, TRANSFER, or any other method)\nand durably stores it in the outbox for asynchronous relay to RabbitMQ. Idempotent on the\nderived idempotency key (provider.name + eventId + optional Idempotency-Key header).",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "payments"
                ],
                "summary": "Ingest a payment event",
                "parameters": [
                    {
                        "type": "string",
                        "description": "Optional client-supplied idempotency key",
                        "name": "Idempotency-Key",
                        "in": "header"
                    },
                    {
                        "type": "string",
                        "description": "Payment ID (PUT/PATCH only)",
                        "name": "id",
                        "in": "path"
                    },
                    {
                        "description": "Payment event payload",
                        "name": "payment",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/internal_adapter_http.PaymentRequest"
                        }
                    }
                ],
                "responses": {
                    "201": {
                        "description": "Created",
                        "schema": {
                            "$ref": "#/definitions/internal_adapter_http.PaymentResponse"
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "$ref": "#/definitions/internal_adapter_http.ErrorResponse"
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "$ref": "#/definitions/internal_adapter_http.ErrorResponse"
                        }
                    }
                }
            },
            "patch": {
                "description": "Accepts a payment-provider webhook-shaped event (PIX, BOLETO, TRANSFER, or any other method)\nand durably stores it in the outbox for asynchronous relay to RabbitMQ. Idempotent on the\nderived idempotency key (provider.name + eventId + optional Idempotency-Key header).",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "payments"
                ],
                "summary": "Ingest a payment event",
                "parameters": [
                    {
                        "type": "string",
                        "description": "Optional client-supplied idempotency key",
                        "name": "Idempotency-Key",
                        "in": "header"
                    },
                    {
                        "type": "string",
                        "description": "Payment ID (PUT/PATCH only)",
                        "name": "id",
                        "in": "path"
                    },
                    {
                        "description": "Payment event payload",
                        "name": "payment",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/internal_adapter_http.PaymentRequest"
                        }
                    }
                ],
                "responses": {
                    "201": {
                        "description": "Created",
                        "schema": {
                            "$ref": "#/definitions/internal_adapter_http.PaymentResponse"
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "$ref": "#/definitions/internal_adapter_http.ErrorResponse"
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "$ref": "#/definitions/internal_adapter_http.ErrorResponse"
                        }
                    }
                }
            }
        },
        "/healthz": {
            "get": {
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "health"
                ],
                "summary": "Health check",
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "type": "object",
                            "additionalProperties": {
                                "type": "string"
                            }
                        }
                    }
                }
            }
        }
    },
    "definitions": {
        "internal_adapter_http.ErrorResponse": {
            "type": "object",
            "properties": {
                "detail": {
                    "type": "string"
                },
                "error": {
                    "type": "string"
                }
            }
        },
        "internal_adapter_http.PaymentDataDTO": {
            "type": "object",
            "properties": {
                "amount": {
                    "type": "number"
                },
                "currency": {
                    "type": "string"
                },
                "method": {
                    "type": "string"
                },
                "payerId": {
                    "type": "string"
                },
                "paymentId": {
                    "type": "string"
                },
                "recipientId": {
                    "type": "string"
                }
            }
        },
        "internal_adapter_http.PaymentRequest": {
            "description": "Inbound payment event. Mirrors a payment-provider webhook: a generic envelope (eventId, provider, payment, occurredAt) plus a method-specific sibling object (e.g. \"pix\" or \"boleto\") named after payment.method lowercased.",
            "type": "object",
            "properties": {
                "eventId": {
                    "type": "string"
                },
                "occurredAt": {
                    "type": "string"
                },
                "payment": {
                    "$ref": "#/definitions/internal_adapter_http.PaymentDataDTO"
                },
                "provider": {
                    "$ref": "#/definitions/internal_adapter_http.ProviderDTO"
                }
            }
        },
        "internal_adapter_http.PaymentResponse": {
            "type": "object",
            "properties": {
                "idempotencyKey": {
                    "type": "string"
                },
                "paymentId": {
                    "type": "string"
                },
                "status": {
                    "description": "\"accepted\" | \"duplicate\"",
                    "type": "string"
                }
            }
        },
        "internal_adapter_http.ProviderDTO": {
            "type": "object",
            "properties": {
                "name": {
                    "type": "string"
                },
                "providerPaymentId": {
                    "type": "string"
                }
            }
        }
    }
}`

// SwaggerInfo holds exported Swagger Info so clients can modify it
var SwaggerInfo = &swag.Spec{
	Version:          "1.0",
	Host:             "",
	BasePath:         "/",
	Schemes:          []string{},
	Title:            "Transaction Outbox — Ingestion API",
	Description:      "Accepts payment-provider webhook-shaped events and durably stores them in the\ntransactional outbox for asynchronous relay to RabbitMQ.",
	InfoInstanceName: "swagger",
	SwaggerTemplate:  docTemplate,
	LeftDelim:        "{{",
	RightDelim:       "}}",
}

func init() {
	swag.Register(SwaggerInfo.InstanceName(), SwaggerInfo)
}
